platform: linux

image_resource:
  type: docker-image
  source: 
    repository: maven
    tag: 3-jdk-8-alpine

inputs:
- name: ad-authenticator

outputs:
- name: package-ouput
  
run:
  path: ./ad-authenticator/src/main/ci/package.sh

